name: GitHub Actions Security Analysis

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "security-analysis.yml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "security-analysis.yml"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run actionlint
        run: go run github.com/rhysd/actionlint/cmd/actionlint@v1.7.12

  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      actions: read # read workflow artifacts/results for analysis
      contents: read # read repo content for workflow scan
      security-events: write # publish SARIF findings to Code Scanning
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
