name: GitHub Actions Security Analysis

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "security-analysis.yml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - "security-analysis.yml"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Run actionlint
        run: go run github.com/rhysd/actionlint/cmd/actionlint@v1.7.12

  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      actions: read # read workflow artifacts/results for analysis
      contents: read # read repo content for workflow scan
      security-events: write # publish SARIF findings to Code Scanning
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
